version: '2'

services:
  # web
  bb_web:
    build: ./bb_web
    command: bash -c "/code/wait-for.sh db_web:3307 --timeout=60 & python3 ./bb_web/manage.py runserver 0.0.0.0:8001"
    # command: bash -c "python3 ./bb_web/manage.py makemigrations && python3 ./bb_web/manage.py migrate && python3 ./bb_web/manage.py runserver 0.0.0.0:8001"
    volumes:
      - ./bb_web:/code/bb_web
      # - ./bb_web/src/:/code/bb_web/src
      - /tmp/slack_bot/mysqld:/run/mysqld
    ports:
      - 8001:8001
    restart: always
    depends_on:
      - db_web
    links:
      - db_web

  db_web:
    image: mysql:8.0
    container_name: db_web
    ports:
      - "3311:3307"
    expose:
      - "3307"
    # volumes:
    #   - .:/var/lib/mysql
    # volumes:
    #   - /opt/slack_bot/mysql_data:/var/lib/mysql
    #   - /tmp/slack_bot/mysqld:/var/run/mysqld
    volumes:
      - ./mysql1/data:/var/lib/mysql/
      # - ./my.cnf:/root/.my.cnf:ro
      # - ./db_web/conf.d:/etc/mysql/conf.d:ro
      # - ./db_web/logs:/var/log/mysql:rw
      # - ./db_web/initdb.d:/docker-entrypoint-initdb.d:ro
      # # - ./common:${MOUNTED_SHARED_DIRECTORY}:ro
      # - ./auto-generate:/auto-generate:rw
    environment:
      - MYSQL_ROOT_PASSWORD=123qwe!@#
      - MYSQL_DATABASE=db_web
      - MYSQL_USER=ductai26998
      - MYSQL_PASSWORD=ductai26998
      - MYSQL_HOST=localhost
      - MYSQL_TCP_PORT=3307

  # app
  bb_app:
    build: ./bb_app
    command: bash -c "/code/wait-for.sh db_app:3306 --timeout=60 & python3 ./bb_app/manage.py runserver 0.0.0.0:8002"
    # command: bash -c "python3 ./bb_app/manage.py makemigrations && python3 ./bb_app/manage.py migrate && python3 ./bb_app/manage.py runserver 0.0.0.0:8002"
    volumes:
      - ./bb_app:/code/bb_app
      - /tmp/slack_bot/mysqld:/run/mysqld
    ports:
      - 8002:8002
    restart: always
    depends_on:
      - db_app
    links:
      - db_app

  db_app:
    # image: mysql:5.5
    image: mysql:8.0
    container_name: db_app
    ports:
      - "3312:3306"
    # expose:
    #   - "3307"
    # volumes:
    #   - .:/var/lib/mysql
    # volumes:
    #   - /opt/slack_bot/mysql_data:/var/lib/mysql
    #   - /tmp/slack_bot/mysqld:/var/run/mysqld
    volumes:
      - ./mysql2/data:/var/lib/mysql/
      # - ./my.cnf:/root/.my.cnf:ro
      # - ./db_app/conf.d:/etc/mysql/conf.d:ro
      # - ./db_app/logs:/var/log/mysql:rw
      # - ./db_app/initdb.d:/docker-entrypoint-initdb.d:ro
      # # - ./common:${MOUNTED_SHARED_DIRECTORY}:ro
      # - ./auto-generate:/auto-generate:rw
    environment:
      - MYSQL_ROOT_PASSWORD=123qwe!@#
      - MYSQL_DATABASE=db_app
      - MYSQL_USER=ductai26998
      - MYSQL_PASSWORD=ductai26998
      - MYSQL_HOST=localhost
      # - MYSQL_TCP_PORT=3307
